//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TicketBookingModel", "FK_Premiere_Genre", "Genre", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheatreTicketBooking.DataAccess.Genre), "Premiere", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheatreTicketBooking.DataAccess.Premiere), true)]
[assembly: EdmRelationshipAttribute("TicketBookingModel", "FK_Ticket_Premiere", "Premiere", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheatreTicketBooking.DataAccess.Premiere), "Ticket", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheatreTicketBooking.DataAccess.Ticket), true)]

#endregion

namespace TheatreTicketBooking.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TicketBookingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TicketBookingEntities object using the connection string found in the 'TicketBookingEntities' section of the application configuration file.
        /// </summary>
        public TicketBookingEntities() : base("name=TicketBookingEntities", "TicketBookingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TicketBookingEntities object.
        /// </summary>
        public TicketBookingEntities(string connectionString) : base(connectionString, "TicketBookingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TicketBookingEntities object.
        /// </summary>
        public TicketBookingEntities(EntityConnection connection) : base(connection, "TicketBookingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Genre> Genre
        {
            get
            {
                if ((_Genre == null))
                {
                    _Genre = base.CreateObjectSet<Genre>("Genre");
                }
                return _Genre;
            }
        }
        private ObjectSet<Genre> _Genre;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Premiere> Premiere
        {
            get
            {
                if ((_Premiere == null))
                {
                    _Premiere = base.CreateObjectSet<Premiere>("Premiere");
                }
                return _Premiere;
            }
        }
        private ObjectSet<Premiere> _Premiere;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ticket> Ticket
        {
            get
            {
                if ((_Ticket == null))
                {
                    _Ticket = base.CreateObjectSet<Ticket>("Ticket");
                }
                return _Ticket;
            }
        }
        private ObjectSet<Ticket> _Ticket;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Genre EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGenre(Genre genre)
        {
            base.AddObject("Genre", genre);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Premiere EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPremiere(Premiere premiere)
        {
            base.AddObject("Premiere", premiere);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ticket EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTicket(Ticket ticket)
        {
            base.AddObject("Ticket", ticket);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TicketBookingModel", Name="Genre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Genre : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Genre object.
        /// </summary>
        /// <param name="genreID">Initial value of the GenreID property.</param>
        public static Genre CreateGenre(global::System.Int32 genreID)
        {
            Genre genre = new Genre();
            genre.GenreID = genreID;
            return genre;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenreID
        {
            get
            {
                return _GenreID;
            }
            set
            {
                if (_GenreID != value)
                {
                    OnGenreIDChanging(value);
                    ReportPropertyChanging("GenreID");
                    _GenreID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GenreID");
                    OnGenreIDChanged();
                }
            }
        }
        private global::System.Int32 _GenreID;
        partial void OnGenreIDChanging(global::System.Int32 value);
        partial void OnGenreIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TicketBookingModel", "FK_Premiere_Genre", "Premiere")]
        public EntityCollection<Premiere> Premiere
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Premiere>("TicketBookingModel.FK_Premiere_Genre", "Premiere");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Premiere>("TicketBookingModel.FK_Premiere_Genre", "Premiere", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TicketBookingModel", Name="Premiere")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Premiere : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Premiere object.
        /// </summary>
        /// <param name="premiereID">Initial value of the PremiereID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="ticketCapacity">Initial value of the TicketCapacity property.</param>
        /// <param name="genreID">Initial value of the GenreID property.</param>
        public static Premiere CreatePremiere(global::System.Int32 premiereID, global::System.String name, global::System.Decimal price, global::System.Int32 ticketCapacity, global::System.Int32 genreID)
        {
            Premiere premiere = new Premiere();
            premiere.PremiereID = premiereID;
            premiere.Name = name;
            premiere.Price = price;
            premiere.TicketCapacity = ticketCapacity;
            premiere.GenreID = genreID;
            return premiere;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PremiereID
        {
            get
            {
                return _PremiereID;
            }
            set
            {
                if (_PremiereID != value)
                {
                    OnPremiereIDChanging(value);
                    ReportPropertyChanging("PremiereID");
                    _PremiereID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PremiereID");
                    OnPremiereIDChanged();
                }
            }
        }
        private global::System.Int32 _PremiereID;
        partial void OnPremiereIDChanging(global::System.Int32 value);
        partial void OnPremiereIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TicketCapacity
        {
            get
            {
                return _TicketCapacity;
            }
            set
            {
                OnTicketCapacityChanging(value);
                ReportPropertyChanging("TicketCapacity");
                _TicketCapacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TicketCapacity");
                OnTicketCapacityChanged();
            }
        }
        private global::System.Int32 _TicketCapacity;
        partial void OnTicketCapacityChanging(global::System.Int32 value);
        partial void OnTicketCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GenreID
        {
            get
            {
                return _GenreID;
            }
            set
            {
                OnGenreIDChanging(value);
                ReportPropertyChanging("GenreID");
                _GenreID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GenreID");
                OnGenreIDChanged();
            }
        }
        private global::System.Int32 _GenreID;
        partial void OnGenreIDChanging(global::System.Int32 value);
        partial void OnGenreIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TicketBookingModel", "FK_Premiere_Genre", "Genre")]
        public Genre Genre
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Genre>("TicketBookingModel.FK_Premiere_Genre", "Genre").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Genre>("TicketBookingModel.FK_Premiere_Genre", "Genre").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Genre> GenreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Genre>("TicketBookingModel.FK_Premiere_Genre", "Genre");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Genre>("TicketBookingModel.FK_Premiere_Genre", "Genre", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TicketBookingModel", "FK_Ticket_Premiere", "Ticket")]
        public EntityCollection<Ticket> Ticket
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ticket>("TicketBookingModel.FK_Ticket_Premiere", "Ticket");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ticket>("TicketBookingModel.FK_Ticket_Premiere", "Ticket", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TicketBookingModel", Name="Ticket")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ticket : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ticket object.
        /// </summary>
        /// <param name="ticketID">Initial value of the TicketID property.</param>
        /// <param name="premiereID">Initial value of the PremiereID property.</param>
        public static Ticket CreateTicket(global::System.Int32 ticketID, global::System.Int32 premiereID)
        {
            Ticket ticket = new Ticket();
            ticket.TicketID = ticketID;
            ticket.PremiereID = premiereID;
            return ticket;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TicketID
        {
            get
            {
                return _TicketID;
            }
            set
            {
                if (_TicketID != value)
                {
                    OnTicketIDChanging(value);
                    ReportPropertyChanging("TicketID");
                    _TicketID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TicketID");
                    OnTicketIDChanged();
                }
            }
        }
        private global::System.Int32 _TicketID;
        partial void OnTicketIDChanging(global::System.Int32 value);
        partial void OnTicketIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PremiereID
        {
            get
            {
                return _PremiereID;
            }
            set
            {
                OnPremiereIDChanging(value);
                ReportPropertyChanging("PremiereID");
                _PremiereID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PremiereID");
                OnPremiereIDChanged();
            }
        }
        private global::System.Int32 _PremiereID;
        partial void OnPremiereIDChanging(global::System.Int32 value);
        partial void OnPremiereIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TicketBookingModel", "FK_Ticket_Premiere", "Premiere")]
        public Premiere Premiere
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Premiere>("TicketBookingModel.FK_Ticket_Premiere", "Premiere").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Premiere>("TicketBookingModel.FK_Ticket_Premiere", "Premiere").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Premiere> PremiereReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Premiere>("TicketBookingModel.FK_Ticket_Premiere", "Premiere");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Premiere>("TicketBookingModel.FK_Ticket_Premiere", "Premiere", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
