-- Иерархический запрос
/*
SELECT NAME --,LEVEL
FROM SYSTEM.CATEGORY
WHERE LEVEL = 2
START WITH NAME LIKE 'Ноутб%'-- или ID = 1
CONNECT BY PRIOR ID = ParentCategory;
*/
-- FOR

SELECT * FROM CUSTOMER;
/
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;
  I NUMBER;
BEGIN
  FOR I IN 1 .. 30 LOOP
    INSERT INTO CUSTOMER(ID, FIRSTNAME, LASTNAME, EMAIL)
    VALUES(I, 'Customer' || I, 'LastName', 'customer' || I || '@domain.com');
  END LOOP;
  EXCEPTION 
  WHEN DUP_VAL_ON_INDEX THEN 
    BEGIN
      ROLLBACK;
      DBMS_OUTPUT.ENABLE(100);
      DBMS_OUTPUT.PUT_LINE('INSERT FAILED, ROLLING BACK CHANGES');
    END;
END;

/*
DECLARE 
  TYPE CUSTOMER_TYPE IS TABLE OF CUSTOMER%ROWTYPE INDEX BY PLS_INTEGER;
  ALL_CUSTOMERS CUSTOMER_TYPE;

BEGIN
  SELECT * BULK COLLECT INTO ALL_CUSTOMERS FROM CUSTOMER;
  
  OPEN CURSOR1 (ALL_CUSTOMERS);
  FOR CursorRec IN CURSOR1 LOOP
    
  END LOOP;
END
*/