// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace GoogleCalculatorTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// TestAddOperatorInGoogleSearch - Use 'TestAddOperatorInGoogleSearchParams' to pass parameters into this method.
        /// </summary>
        public void TestAddOperatorInGoogleSearch()
        {
            #region Variable Declarations
            BrowserWindow uIHttpwwwmicrosoftcomiWindow = this.UIHttpwwwmicrosoftcomiWindow;
            HtmlEdit uIПошукGoogleEdit = this.UIGoogleWindowsInterneWindow.UIGoogleDocument.UIПошукGoogleEdit;
            HtmlInputButton uIПошукGoogleButton = this.UIGoogleWindowsInterneWindow.UIGoogleDocument.UIMainPane.UIПошукGoogleButton;
            #endregion

            // Go to web page 'http://google.com/'
            uIHttpwwwmicrosoftcomiWindow.NavigateToUrl(new System.Uri(this.TestAddOperatorInGoogleSearchParams.UIHttpwwwmicrosoftcomiWindowUrl));

            // Type '1+2' in 'Пошук Google' text box
            uIПошукGoogleEdit.Text = this.TestAddOperatorInGoogleSearchParams.UIПошукGoogleEditText;

            // Click 'Пошук Google' button
            Mouse.Click(uIПошукGoogleButton, new Point(38, 23));
        }
        
        /// <summary>
        /// TestGooggleCalculator - Use 'TestGooggleCalculatorParams' to pass parameters into this method.
        /// </summary>
        public void TestGooggleCalculator()
        {
            #region Variable Declarations
            HtmlEdit uIПошукGoogleEdit = this.UIGoogleWindowsInterneWindow.UIGoogleDocument.UIПошукGoogleEdit;
            #endregion

            // Type '1+2' in 'Пошук Google' text box
            uIПошукGoogleEdit.Text = this.TestGooggleCalculatorParams.UIПошукGoogleEditText;

            // Type '{Enter}' in 'Пошук Google' text box
            Keyboard.SendKeys(uIПошукGoogleEdit, this.TestGooggleCalculatorParams.UIПошукGoogleEditSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// ensure_1_plus_2_equal_to_3 - Use 'ensure_1_plus_2_equal_to_3ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ensure_1_plus_2_equal_to_3()
        {
            #region Variable Declarations
            HtmlCell uIItem123Cell = this.UIItem12ПошукGoogleWinWindow1.UIItem12ПошукGoogleDocument.UITopstuffPane.UIItemTable.UIItem123Cell;
            #endregion

            // Verify that '1 + 2 = 3' cell's property 'InnerText' equals '1 + 2 = 3'
            Assert.AreEqual(this.ensure_1_plus_2_equal_to_3ExpectedValues.UIItem123CellInnerText, uIItem123Cell.InnerText);
        }
        
        /// <summary>
        /// TestConversionEngine - Use 'TestConversionEngineParams' to pass parameters into this method.
        /// </summary>
        public void TestConversionEngine()
        {
            #region Variable Declarations
            HtmlEdit uIПошукEdit = this.UIItem12ПошукGoogleWinWindow1.UIItem12ПошукGoogleDocument.UIПошукEdit;
            #endregion

            // Type '1 удав в попугаях' in 'Пошук' text box
            uIПошукEdit.Text = this.TestConversionEngineParams.UIПошукEditText;

            // Type '{Enter}' in 'Пошук' text box
            Keyboard.SendKeys(uIПошукEdit, this.TestConversionEngineParams.UIПошукEditSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// ensure_that_1_python_equal_to_38_parrots - Use 'ensure_that_1_python_equal_to_38_parrotsExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ensure_that_1_python_equal_to_38_parrots()
        {
            #region Variable Declarations
            HtmlCell uIItem1удав38попугаевДCell = this.UIItem12ПошукGoogleWinWindow1.UIItem1удаввпопугаяхПоDocument.UITopstuffPane.UIItemTable.UIItem1удав38попугаевДCell;
            #endregion

            // Verify that '1 удав = 38 попугаев Докладніше про кал' cell's property 'InnerText' contains '1 удав = 38 попугаев'
            StringAssert.Contains(uIItem1удав38попугаевДCell.InnerText, this.ensure_that_1_python_equal_to_38_parrotsExpectedValues.UIItem1удав38попугаевДCellInnerText);
        }
        
        /// <summary>
        /// TestNotepad - Use 'TestNotepadParams' to pass parameters into this method.
        /// </summary>
        public void TestNotepad()
        {
            #region Variable Declarations
            WinButton uIПускButton = this.UIПускWindow.UIПускButton;
            WinMenuItem uIВыполнитьMenuItem = this.UIГлавноеменюWindow.UIItemWindow.UIГлавноеменюClient.UIВыполнитьMenuItem;
            WinComboBox uIОткрытьComboBox = this.UIЗапускпрограммыWindow.UIItemWindow.UIОткрытьComboBox;
            WinButton uIОКButton = this.UIЗапускпрограммыWindow.UIОКWindow.UIОКButton;
            WinEdit uIItemEdit = this.UIБезымянныйБлокнотWindow.UIItemWindow.UIItemEdit;
            WinMenuItem uIСохранитьCtrlSMenuItem = this.UIБезымянныйБлокнотWindow.UIПриложениеMenuBar.UIФайлMenuItem.UIСохранитьCtrlSMenuItem;
            WinComboBox uIИмяфайлаComboBox = this.UIСохранитькакWindow.UIItemWindow.UIИмяфайлаComboBox;
            WinButton uIСохранитьButton = this.UIСохранитькакWindow.UIСохранитьWindow.UIСохранитьButton;
            WinButton uIЗакрытьButton = this.UIБезымянныйБлокнотWindow.UITestfiletxtБлокнотTitleBar.UIЗакрытьButton;
            #endregion

            // Click 'Пуск' button
            Mouse.Click(uIПускButton, new Point(10, 12));

            // Click 'Выполнить...' menu item
            Mouse.Click(uIВыполнитьMenuItem, new Point(21, 9));

            // Select 'notepad' in 'Открыть:' combo box
            uIОткрытьComboBox.EditableItem = this.TestNotepadParams.UIОткрытьComboBoxEditableItem;

            // Click 'ОК' button
            Mouse.Click(uIОКButton, new Point(31, 13));

            // Type 'this is a test' in 'Unknown Name' text box
            uIItemEdit.Text = this.TestNotepadParams.UIItemEditText;

            // Click 'Файл' -> 'Сохранить	Ctrl+S' menu item
            Mouse.Click(uIСохранитьCtrlSMenuItem, new Point(31, 10));

            // Select 'testfile.txt' in 'Имя файла:' combo box
            uIИмяфайлаComboBox.EditableItem = this.TestNotepadParams.UIИмяфайлаComboBoxEditableItem;

            // Click 'Со&хранить' button
            Mouse.Click(uIСохранитьButton, new Point(55, 9));

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(10, 8));

            // Launch '%windir%\system32\notepad.exe' with arguments 'C:\Documents and Settings\manekovskiy\Desktop\testfile.txt'
            ApplicationUnderTest notepadApplication = ApplicationUnderTest.Launch(this.TestNotepadParams.ExePath, this.TestNotepadParams.AlternateExePath, "C:\\Documents and Settings\\manekovskiy\\Desktop\\testfile.txt");
        }
        
        /// <summary>
        /// ensure_text_can_be_saved - Use 'ensure_text_can_be_savedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void ensure_text_can_be_saved()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIБезымянныйБлокнотWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Verify that 'Unknown Name' text box's property 'Text' equals 'this is a test'
            Assert.AreEqual(this.ensure_text_can_be_savedExpectedValues.UIItemEditText, uIItemEdit.Text);
        }
        
        #region Properties
        public virtual TestAddOperatorInGoogleSearchParams TestAddOperatorInGoogleSearchParams
        {
            get
            {
                if ((this.mTestAddOperatorInGoogleSearchParams == null))
                {
                    this.mTestAddOperatorInGoogleSearchParams = new TestAddOperatorInGoogleSearchParams();
                }
                return this.mTestAddOperatorInGoogleSearchParams;
            }
        }
        
        public virtual TestGooggleCalculatorParams TestGooggleCalculatorParams
        {
            get
            {
                if ((this.mTestGooggleCalculatorParams == null))
                {
                    this.mTestGooggleCalculatorParams = new TestGooggleCalculatorParams();
                }
                return this.mTestGooggleCalculatorParams;
            }
        }
        
        public virtual ensure_1_plus_2_equal_to_3ExpectedValues ensure_1_plus_2_equal_to_3ExpectedValues
        {
            get
            {
                if ((this.mensure_1_plus_2_equal_to_3ExpectedValues == null))
                {
                    this.mensure_1_plus_2_equal_to_3ExpectedValues = new ensure_1_plus_2_equal_to_3ExpectedValues();
                }
                return this.mensure_1_plus_2_equal_to_3ExpectedValues;
            }
        }
        
        public virtual TestConversionEngineParams TestConversionEngineParams
        {
            get
            {
                if ((this.mTestConversionEngineParams == null))
                {
                    this.mTestConversionEngineParams = new TestConversionEngineParams();
                }
                return this.mTestConversionEngineParams;
            }
        }
        
        public virtual ensure_that_1_python_equal_to_38_parrotsExpectedValues ensure_that_1_python_equal_to_38_parrotsExpectedValues
        {
            get
            {
                if ((this.mensure_that_1_python_equal_to_38_parrotsExpectedValues == null))
                {
                    this.mensure_that_1_python_equal_to_38_parrotsExpectedValues = new ensure_that_1_python_equal_to_38_parrotsExpectedValues();
                }
                return this.mensure_that_1_python_equal_to_38_parrotsExpectedValues;
            }
        }
        
        public virtual TestNotepadParams TestNotepadParams
        {
            get
            {
                if ((this.mTestNotepadParams == null))
                {
                    this.mTestNotepadParams = new TestNotepadParams();
                }
                return this.mTestNotepadParams;
            }
        }
        
        public virtual ensure_text_can_be_savedExpectedValues ensure_text_can_be_savedExpectedValues
        {
            get
            {
                if ((this.mensure_text_can_be_savedExpectedValues == null))
                {
                    this.mensure_text_can_be_savedExpectedValues = new ensure_text_can_be_savedExpectedValues();
                }
                return this.mensure_text_can_be_savedExpectedValues;
            }
        }
        
        public UIHttpwwwmicrosoftcomiWindow UIHttpwwwmicrosoftcomiWindow
        {
            get
            {
                if ((this.mUIHttpwwwmicrosoftcomiWindow == null))
                {
                    this.mUIHttpwwwmicrosoftcomiWindow = new UIHttpwwwmicrosoftcomiWindow();
                }
                return this.mUIHttpwwwmicrosoftcomiWindow;
            }
        }
        
        public UIGoogleWindowsInterneWindow UIGoogleWindowsInterneWindow
        {
            get
            {
                if ((this.mUIGoogleWindowsInterneWindow == null))
                {
                    this.mUIGoogleWindowsInterneWindow = new UIGoogleWindowsInterneWindow();
                }
                return this.mUIGoogleWindowsInterneWindow;
            }
        }
        
        public UIItem12ПошукGoogleWinWindow UIItem12ПошукGoogleWinWindow
        {
            get
            {
                if ((this.mUIItem12ПошукGoogleWinWindow == null))
                {
                    this.mUIItem12ПошукGoogleWinWindow = new UIItem12ПошукGoogleWinWindow();
                }
                return this.mUIItem12ПошукGoogleWinWindow;
            }
        }
        
        public UIItem12ПошукGoogleWinWindow1 UIItem12ПошукGoogleWinWindow1
        {
            get
            {
                if ((this.mUIItem12ПошукGoogleWinWindow1 == null))
                {
                    this.mUIItem12ПошукGoogleWinWindow1 = new UIItem12ПошукGoogleWinWindow1();
                }
                return this.mUIItem12ПошукGoogleWinWindow1;
            }
        }
        
        public UIПускWindow UIПускWindow
        {
            get
            {
                if ((this.mUIПускWindow == null))
                {
                    this.mUIПускWindow = new UIПускWindow();
                }
                return this.mUIПускWindow;
            }
        }
        
        public UIГлавноеменюWindow UIГлавноеменюWindow
        {
            get
            {
                if ((this.mUIГлавноеменюWindow == null))
                {
                    this.mUIГлавноеменюWindow = new UIГлавноеменюWindow();
                }
                return this.mUIГлавноеменюWindow;
            }
        }
        
        public UIЗапускпрограммыWindow UIЗапускпрограммыWindow
        {
            get
            {
                if ((this.mUIЗапускпрограммыWindow == null))
                {
                    this.mUIЗапускпрограммыWindow = new UIЗапускпрограммыWindow();
                }
                return this.mUIЗапускпрограммыWindow;
            }
        }
        
        public UIБезымянныйБлокнотWindow UIБезымянныйБлокнотWindow
        {
            get
            {
                if ((this.mUIБезымянныйБлокнотWindow == null))
                {
                    this.mUIБезымянныйБлокнотWindow = new UIБезымянныйБлокнотWindow();
                }
                return this.mUIБезымянныйБлокнотWindow;
            }
        }
        
        public UIСохранитькакWindow UIСохранитькакWindow
        {
            get
            {
                if ((this.mUIСохранитькакWindow == null))
                {
                    this.mUIСохранитькакWindow = new UIСохранитькакWindow();
                }
                return this.mUIСохранитькакWindow;
            }
        }
        #endregion
        
        #region Fields
        private TestAddOperatorInGoogleSearchParams mTestAddOperatorInGoogleSearchParams;
        
        private TestGooggleCalculatorParams mTestGooggleCalculatorParams;
        
        private ensure_1_plus_2_equal_to_3ExpectedValues mensure_1_plus_2_equal_to_3ExpectedValues;
        
        private TestConversionEngineParams mTestConversionEngineParams;
        
        private ensure_that_1_python_equal_to_38_parrotsExpectedValues mensure_that_1_python_equal_to_38_parrotsExpectedValues;
        
        private TestNotepadParams mTestNotepadParams;
        
        private ensure_text_can_be_savedExpectedValues mensure_text_can_be_savedExpectedValues;
        
        private UIHttpwwwmicrosoftcomiWindow mUIHttpwwwmicrosoftcomiWindow;
        
        private UIGoogleWindowsInterneWindow mUIGoogleWindowsInterneWindow;
        
        private UIItem12ПошукGoogleWinWindow mUIItem12ПошукGoogleWinWindow;
        
        private UIItem12ПошукGoogleWinWindow1 mUIItem12ПошукGoogleWinWindow1;
        
        private UIПускWindow mUIПускWindow;
        
        private UIГлавноеменюWindow mUIГлавноеменюWindow;
        
        private UIЗапускпрограммыWindow mUIЗапускпрограммыWindow;
        
        private UIБезымянныйБлокнотWindow mUIБезымянныйБлокнотWindow;
        
        private UIСохранитькакWindow mUIСохранитькакWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestAddOperatorInGoogleSearch'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class TestAddOperatorInGoogleSearchParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://google.com/'
        /// </summary>
        public string UIHttpwwwmicrosoftcomiWindowUrl = "http://google.com/";
        
        /// <summary>
        /// Type '1+2' in 'Пошук Google' text box
        /// </summary>
        public string UIПошукGoogleEditText = "1+2";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestGooggleCalculator'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class TestGooggleCalculatorParams
    {
        
        #region Fields
        /// <summary>
        /// Type '1+2' in 'Пошук Google' text box
        /// </summary>
        public string UIПошукGoogleEditText = "1+2";
        
        /// <summary>
        /// Type '{Enter}' in 'Пошук Google' text box
        /// </summary>
        public string UIПошукGoogleEditSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ensure_1_plus_2_equal_to_3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class ensure_1_plus_2_equal_to_3ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that '1 + 2 = 3' cell's property 'InnerText' equals '1 + 2 = 3'
        /// </summary>
        public string UIItem123CellInnerText = "1 + 2 = 3";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestConversionEngine'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class TestConversionEngineParams
    {
        
        #region Fields
        /// <summary>
        /// Type '1 удав в попугаях' in 'Пошук' text box
        /// </summary>
        public string UIПошукEditText = "1 удав в попугаях";
        
        /// <summary>
        /// Type '{Enter}' in 'Пошук' text box
        /// </summary>
        public string UIПошукEditSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ensure_that_1_python_equal_to_38_parrots'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class ensure_that_1_python_equal_to_38_parrotsExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that '1 удав = 38 попугаев Докладніше про кал' cell's property 'InnerText' contains '1 удав = 38 попугаев'
        /// </summary>
        public string UIItem1удав38попугаевДCellInnerText = "1 удав = 38 попугаев";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestNotepad'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class TestNotepadParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'notepad' in 'Открыть:' combo box
        /// </summary>
        public string UIОткрытьComboBoxEditableItem = "notepad";
        
        /// <summary>
        /// Type 'this is a test' in 'Unknown Name' text box
        /// </summary>
        public string UIItemEditText = "this is a test";
        
        /// <summary>
        /// Select 'testfile.txt' in 'Имя файла:' combo box
        /// </summary>
        public string UIИмяфайлаComboBoxEditableItem = "testfile.txt";
        
        /// <summary>
        /// Launch '%windir%\system32\notepad.exe' with arguments 'C:\Documents and Settings\manekovskiy\Desktop\testfile.txt'
        /// </summary>
        public string ExePath = "C:\\WINDOWS\\system32\\notepad.exe";
        
        /// <summary>
        /// Launch '%windir%\system32\notepad.exe' with arguments 'C:\Documents and Settings\manekovskiy\Desktop\testfile.txt'
        /// </summary>
        public string AlternateExePath = "%windir%\\system32\\notepad.exe";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ensure_text_can_be_saved'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class ensure_text_can_be_savedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'Unknown Name' text box's property 'Text' equals 'this is a test'
        /// </summary>
        public string UIItemEditText = "this is a test";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIHttpwwwmicrosoftcomiWindow : BrowserWindow
    {
        
        public UIHttpwwwmicrosoftcomiWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "http://www.microsoft.com/isapi/redir.dll?prd=ie&pver=6&ar=msnhome";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("http://www.microsoft.com/isapi/redir.dll?prd=ie&pver=6&ar=msnhome");
            this.WindowTitles.Add("http://home.microsoft.com/");
            this.WindowTitles.Add("http://www.msn.com/");
            this.WindowTitles.Add("MSN.com");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIGoogleWindowsInterneWindow : BrowserWindow
    {
        
        public UIGoogleWindowsInterneWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Google";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Google");
            this.WindowTitles.Add("1+2 - Пошук Google");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGoogleDocument UIGoogleDocument
        {
            get
            {
                if ((this.mUIGoogleDocument == null))
                {
                    this.mUIGoogleDocument = new UIGoogleDocument(this);
                }
                return this.mUIGoogleDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGoogleDocument mUIGoogleDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIGoogleDocument : HtmlDocument
    {
        
        public UIGoogleDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.google.com.ua/";
            this.WindowTitles.Add("Google");
            this.WindowTitles.Add("1+2 - Пошук Google");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIПошукGoogleEdit
        {
            get
            {
                if ((this.mUIПошукGoogleEdit == null))
                {
                    this.mUIПошукGoogleEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIПошукGoogleEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIПошукGoogleEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUIПошукGoogleEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIПошукGoogleEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIПошукGoogleEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Пошук Google";
                    this.mUIПошукGoogleEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "lst tiah";
                    this.mUIПошукGoogleEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "style=\"BORDER-BOTTOM: #999 1px solid; BO";
                    this.mUIПошукGoogleEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIПошукGoogleEdit.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUIПошукGoogleEdit;
            }
        }
        
        public UIMainPane UIMainPane
        {
            get
            {
                if ((this.mUIMainPane == null))
                {
                    this.mUIMainPane = new UIMainPane(this);
                }
                return this.mUIMainPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIПошукGoogleEdit;
        
        private UIMainPane mUIMainPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIMainPane : HtmlDiv
    {
        
        public UIMainPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "main";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "\r\n\r\nУкраїна\r\n\r\n \r\nРозширений пошук\r\nМовн";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=main";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIПошукGoogleButton
        {
            get
            {
                if ((this.mUIПошукGoogleButton == null))
                {
                    this.mUIПошукGoogleButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIПошукGoogleButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIПошукGoogleButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIПошукGoogleButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Пошук Google";
                    this.mUIПошукGoogleButton.FilterProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIПошукGoogleButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIПошукGoogleButton.FilterProperties[HtmlButton.PropertyNames.Class] = "lsb";
                    this.mUIПошукGoogleButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "style=\"PADDING-BOTTOM: 0px; PADDING-LEFT";
                    this.mUIПошукGoogleButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "12";
                    this.mUIПошукGoogleButton.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUIПошукGoogleButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIПошукGoogleButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem12ПошукGoogleWinWindow : BrowserWindow
    {
        
        public UIItem12ПошукGoogleWinWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "1+2 - Пошук Google";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("1+2 - Пошук Google");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIItem12ПошукGoogleDocument UIItem12ПошукGoogleDocument
        {
            get
            {
                if ((this.mUIItem12ПошукGoogleDocument == null))
                {
                    this.mUIItem12ПошукGoogleDocument = new UIItem12ПошукGoogleDocument(this);
                }
                return this.mUIItem12ПошукGoogleDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIItem12ПошукGoogleDocument mUIItem12ПошукGoogleDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem12ПошукGoogleDocument : HtmlDocument
    {
        
        public UIItem12ПошукGoogleDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "1+2 - Пошук Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.google.com.ua/#hl=uk&source=hp&biw=1276&bih=837&q=1%2B2&aq=f&aqi=g1&aq" +
                "l=&oq=&fp=efb94b2d0ed3f111";
            this.WindowTitles.Add("1+2 - Пошук Google");
            #endregion
        }
        
        #region Properties
        public UITopstuffPane UITopstuffPane
        {
            get
            {
                if ((this.mUITopstuffPane == null))
                {
                    this.mUITopstuffPane = new UITopstuffPane(this);
                }
                return this.mUITopstuffPane;
            }
        }
        #endregion
        
        #region Fields
        private UITopstuffPane mUITopstuffPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UITopstuffPane : HtmlSpan
    {
        
        public UITopstuffPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "topstuff";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = " 1 + 2 = 3\r\n\r\nШукати документи, що містя";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=topstuff";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "7";
            this.WindowTitles.Add("1+2 - Пошук Google");
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = " 1 + 2 = 3";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=std";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "3";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "std";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("1+2 - Пошук Google");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItem123Cell
        {
            get
            {
                if ((this.mUIItem123Cell == null))
                {
                    this.mUIItem123Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem123Cell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItem123Cell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItem123Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.InnerText] = "1 + 2 = 3";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "style=\"VERTICAL-ALIGN: top\"";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "3";
                    this.mUIItem123Cell.WindowTitles.Add("1+2 - Пошук Google");
                    #endregion
                }
                return this.mUIItem123Cell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItem123Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem12ПошукGoogleWinWindow1 : BrowserWindow
    {
        
        public UIItem12ПошукGoogleWinWindow1()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "1+2 - Пошук Google";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("1+2 - Пошук Google");
            this.WindowTitles.Add("1 удав в попугаях - Пошук Google");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIItem12ПошукGoogleDocument1 UIItem12ПошукGoogleDocument
        {
            get
            {
                if ((this.mUIItem12ПошукGoogleDocument == null))
                {
                    this.mUIItem12ПошукGoogleDocument = new UIItem12ПошукGoogleDocument1(this);
                }
                return this.mUIItem12ПошукGoogleDocument;
            }
        }
        
        public UIItem1удаввпопугаяхПоDocument UIItem1удаввпопугаяхПоDocument
        {
            get
            {
                if ((this.mUIItem1удаввпопугаяхПоDocument == null))
                {
                    this.mUIItem1удаввпопугаяхПоDocument = new UIItem1удаввпопугаяхПоDocument(this);
                }
                return this.mUIItem1удаввпопугаяхПоDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIItem12ПошукGoogleDocument1 mUIItem12ПошукGoogleDocument;
        
        private UIItem1удаввпопугаяхПоDocument mUIItem1удаввпопугаяхПоDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem12ПошукGoogleDocument1 : HtmlDocument
    {
        
        public UIItem12ПошукGoogleDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "1+2 - Пошук Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.google.com.ua/#hl=uk&source=hp&biw=788&bih=435&q=1%2B2&aq=f&aqi=g1&aql" +
                "=&oq=&fp=efb94b2d0ed3f111";
            this.WindowTitles.Add("1+2 - Пошук Google");
            #endregion
        }
        
        #region Properties
        public UITopstuffPane1 UITopstuffPane
        {
            get
            {
                if ((this.mUITopstuffPane == null))
                {
                    this.mUITopstuffPane = new UITopstuffPane1(this);
                }
                return this.mUITopstuffPane;
            }
        }
        
        public HtmlEdit UIПошукEdit
        {
            get
            {
                if ((this.mUIПошукEdit == null))
                {
                    this.mUIПошукEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIПошукEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIПошукEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUIПошукEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIПошукEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIПошукEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = "Пошук";
                    this.mUIПошукEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "lst";
                    this.mUIПошукEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=lst title=Пошук value=1+2 maxLengt";
                    this.mUIПошукEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIПошукEdit.WindowTitles.Add("1+2 - Пошук Google");
                    #endregion
                }
                return this.mUIПошукEdit;
            }
        }
        #endregion
        
        #region Fields
        private UITopstuffPane1 mUITopstuffPane;
        
        private HtmlEdit mUIПошукEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UITopstuffPane1 : HtmlSpan
    {
        
        public UITopstuffPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "topstuff";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = " 1 + 2 = 3\r\n\r\nШукати документи, що містя";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=topstuff";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "7";
            this.WindowTitles.Add("1+2 - Пошук Google");
            #endregion
        }
        
        #region Properties
        public UIItemTable1 UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable1(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable1 mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemTable1 : HtmlTable
    {
        
        public UIItemTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = " 1 + 2 = 3";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=std";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "3";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "std";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("1+2 - Пошук Google");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItem123Cell
        {
            get
            {
                if ((this.mUIItem123Cell == null))
                {
                    this.mUIItem123Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem123Cell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItem123Cell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItem123Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.InnerText] = "1 + 2 = 3";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "style=\"VERTICAL-ALIGN: top\"";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItem123Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "3";
                    this.mUIItem123Cell.WindowTitles.Add("1+2 - Пошук Google");
                    #endregion
                }
                return this.mUIItem123Cell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItem123Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItem1удаввпопугаяхПоDocument : HtmlDocument
    {
        
        public UIItem1удаввпопугаяхПоDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "1 удав в попугаях - Пошук Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://www.google.com.ua/#hl=uk&biw=772&bih=419&q=1+%D1%83%D0%B4%D0%B0%D0%B2+%D0%" +
                "B2+%D0%BF%D0%BE%D0%BF%D1%83%D0%B3%D0%B0%D1%8F%D1%85&aq=0&aqi=g3&aql=&oq=1+%D1%83" +
                "%D0%B4%D0%B0%D0%B2&fp=efb94b2d0ed3f111";
            this.WindowTitles.Add("1 удав в попугаях - Пошук Google");
            #endregion
        }
        
        #region Properties
        public UITopstuffPane2 UITopstuffPane
        {
            get
            {
                if ((this.mUITopstuffPane == null))
                {
                    this.mUITopstuffPane = new UITopstuffPane2(this);
                }
                return this.mUITopstuffPane;
            }
        }
        #endregion
        
        #region Fields
        private UITopstuffPane2 mUITopstuffPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UITopstuffPane2 : HtmlSpan
    {
        
        public UITopstuffPane2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "topstuff";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = " 1 удав = 38 попугаев\r\nДокладніше про ка";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=topstuff";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "7";
            this.WindowTitles.Add("1 удав в попугаях - Пошук Google");
            #endregion
        }
        
        #region Properties
        public UIItemTable2 UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable2(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable2 mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemTable2 : HtmlTable
    {
        
        public UIItemTable2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = " 1 удав = 38 попугаев\r\nДокладніше про ка";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=std";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "3";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "std";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("1 удав в попугаях - Пошук Google");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIItem1удав38попугаевДCell
        {
            get
            {
                if ((this.mUIItem1удав38попугаевДCell == null))
                {
                    this.mUIItem1удав38попугаевДCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem1удав38попугаевДCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItem1удав38попугаевДCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItem1удав38попугаевДCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem1удав38попугаевДCell.FilterProperties[HtmlCell.PropertyNames.InnerText] = "1 удав = 38 попугаев\r\nДокладніше про кал";
                    this.mUIItem1удав38попугаевДCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "style=\"VERTICAL-ALIGN: top\"";
                    this.mUIItem1удав38попугаевДCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIItem1удав38попугаевДCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIItem1удав38попугаевДCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItem1удав38попугаевДCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "3";
                    this.mUIItem1удав38попугаевДCell.WindowTitles.Add("1 удав в попугаях - Пошук Google");
                    #endregion
                }
                return this.mUIItem1удав38попугаевДCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIItem1удав38попугаевДCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIПускWindow : WinWindow
    {
        
        public UIПускWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Пуск";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("Пуск");
            #endregion
        }
        
        #region Properties
        public WinButton UIПускButton
        {
            get
            {
                if ((this.mUIПускButton == null))
                {
                    this.mUIПускButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIПускButton.SearchProperties[WinButton.PropertyNames.Name] = "Пуск";
                    this.mUIПускButton.WindowTitles.Add("Пуск");
                    #endregion
                }
                return this.mUIПускButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIПускButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIГлавноеменюWindow : WinWindow
    {
        
        public UIГлавноеменюWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Главное меню";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DV2ControlHost";
            this.WindowTitles.Add("Главное меню");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "3";
            this.WindowTitles.Add("Главное меню");
            #endregion
        }
        
        #region Properties
        public UIГлавноеменюClient UIГлавноеменюClient
        {
            get
            {
                if ((this.mUIГлавноеменюClient == null))
                {
                    this.mUIГлавноеменюClient = new UIГлавноеменюClient(this);
                }
                return this.mUIГлавноеменюClient;
            }
        }
        #endregion
        
        #region Fields
        private UIГлавноеменюClient mUIГлавноеменюClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIГлавноеменюClient : WinClient
    {
        
        public UIГлавноеменюClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Главное меню");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIВыполнитьMenuItem
        {
            get
            {
                if ((this.mUIВыполнитьMenuItem == null))
                {
                    this.mUIВыполнитьMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIВыполнитьMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Выполнить...";
                    this.mUIВыполнитьMenuItem.WindowTitles.Add("Главное меню");
                    #endregion
                }
                return this.mUIВыполнитьMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIВыполнитьMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIЗапускпрограммыWindow : WinWindow
    {
        
        public UIЗапускпрограммыWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Запуск программы";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Запуск программы");
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIОКWindow UIОКWindow
        {
            get
            {
                if ((this.mUIОКWindow == null))
                {
                    this.mUIОКWindow = new UIОКWindow(this);
                }
                return this.mUIОКWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow;
        
        private UIОКWindow mUIОКWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "12298";
            this.WindowTitles.Add("Запуск программы");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIОткрытьComboBox
        {
            get
            {
                if ((this.mUIОткрытьComboBox == null))
                {
                    this.mUIОткрытьComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIОткрытьComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Открыть:";
                    this.mUIОткрытьComboBox.WindowTitles.Add("Запуск программы");
                    #endregion
                }
                return this.mUIОткрытьComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIОткрытьComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIОКWindow : WinWindow
    {
        
        public UIОКWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Запуск программы");
            #endregion
        }
        
        #region Properties
        public WinButton UIОКButton
        {
            get
            {
                if ((this.mUIОКButton == null))
                {
                    this.mUIОКButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIОКButton.SearchProperties[WinButton.PropertyNames.Name] = "ОК";
                    this.mUIОКButton.WindowTitles.Add("Запуск программы");
                    #endregion
                }
                return this.mUIОКButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОКButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIБезымянныйБлокнотWindow : WinWindow
    {
        
        public UIБезымянныйБлокнотWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Безымянный - Блокнот";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Notepad";
            this.WindowTitles.Add("Безымянный - Блокнот");
            this.WindowTitles.Add("testfile.txt - Блокнот");
            #endregion
        }
        
        #region Properties
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIПриложениеMenuBar UIПриложениеMenuBar
        {
            get
            {
                if ((this.mUIПриложениеMenuBar == null))
                {
                    this.mUIПриложениеMenuBar = new UIПриложениеMenuBar(this);
                }
                return this.mUIПриложениеMenuBar;
            }
        }
        
        public UITestfiletxtБлокнотTitleBar UITestfiletxtБлокнотTitleBar
        {
            get
            {
                if ((this.mUITestfiletxtБлокнотTitleBar == null))
                {
                    this.mUITestfiletxtБлокнотTitleBar = new UITestfiletxtБлокнотTitleBar(this);
                }
                return this.mUITestfiletxtБлокнотTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow2 mUIItemWindow;
        
        private UIПриложениеMenuBar mUIПриложениеMenuBar;
        
        private UITestfiletxtБлокнотTitleBar mUITestfiletxtБлокнотTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "15";
            this.WindowTitles.Add("Безымянный - Блокнот");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("Безымянный - Блокнот");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIПриложениеMenuBar : WinMenuBar
    {
        
        public UIПриложениеMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Приложение";
            this.WindowTitles.Add("Безымянный - Блокнот");
            #endregion
        }
        
        #region Properties
        public UIФайлMenuItem UIФайлMenuItem
        {
            get
            {
                if ((this.mUIФайлMenuItem == null))
                {
                    this.mUIФайлMenuItem = new UIФайлMenuItem(this);
                }
                return this.mUIФайлMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIФайлMenuItem mUIФайлMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIФайлMenuItem : WinMenuItem
    {
        
        public UIФайлMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Файл";
            this.WindowTitles.Add("Безымянный - Блокнот");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIСохранитьCtrlSMenuItem
        {
            get
            {
                if ((this.mUIСохранитьCtrlSMenuItem == null))
                {
                    this.mUIСохранитьCtrlSMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIСохранитьCtrlSMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Сохранить\tCtrl+S";
                    this.mUIСохранитьCtrlSMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIСохранитьCtrlSMenuItem.WindowTitles.Add("Безымянный - Блокнот");
                    #endregion
                }
                return this.mUIСохранитьCtrlSMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIСохранитьCtrlSMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UITestfiletxtБлокнотTitleBar : WinTitleBar
    {
        
        public UITestfiletxtБлокнотTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("testfile.txt - Блокнот");
            #endregion
        }
        
        #region Properties
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("testfile.txt - Блокнот");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIЗакрытьButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIСохранитькакWindow : WinWindow
    {
        
        public UIСохранитькакWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Сохранить как";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Сохранить как");
            #endregion
        }
        
        #region Properties
        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIСохранитьWindow UIСохранитьWindow
        {
            get
            {
                if ((this.mUIСохранитьWindow == null))
                {
                    this.mUIСохранитьWindow = new UIСохранитьWindow(this);
                }
                return this.mUIСохранитьWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow3 mUIItemWindow;
        
        private UIСохранитьWindow mUIСохранитьWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1148";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Сохранить как");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIИмяфайлаComboBox
        {
            get
            {
                if ((this.mUIИмяфайлаComboBox == null))
                {
                    this.mUIИмяфайлаComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIИмяфайлаComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Имя файла:";
                    this.mUIИмяфайлаComboBox.WindowTitles.Add("Сохранить как");
                    #endregion
                }
                return this.mUIИмяфайлаComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIИмяфайлаComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30319.1")]
    public class UIСохранитьWindow : WinWindow
    {
        
        public UIСохранитьWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Сохранить как");
            #endregion
        }
        
        #region Properties
        public WinButton UIСохранитьButton
        {
            get
            {
                if ((this.mUIСохранитьButton == null))
                {
                    this.mUIСохранитьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIСохранитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Сохранить";
                    this.mUIСохранитьButton.WindowTitles.Add("Сохранить как");
                    #endregion
                }
                return this.mUIСохранитьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIСохранитьButton;
        #endregion
    }
}
